<a href="https://colab.research.google.com/github/walterehickmanII/neural-network-challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [56]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras import layers
from tensorflow.keras.layers import Input, Dense, Dropout
from sklearn.preprocessing import OneHotEncoder
#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [45]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [46]:
# Create y_df with the Attrition and Department columns
y_attrition_df = attrition_df[['Attrition', 'Department']]
y_attrition_df.head()

Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [47]:
# Create a list of at least 10 column names to use as X data
selected_columns = ['Age'
                  , 'HourlyRate'
                  , 'YearsAtCompany'
                  , 'JobLevel'
                  , 'JobSatisfaction'
                  , 'PerformanceRating'
                  , 'Education'
                  , 'WorkLifeBalance'
                  , 'DistanceFromHome'
                  , 'YearsSinceLastPromotion']



# Create X_df using your selected columns
X_attrition_df = attrition_df[selected_columns]

# Show the data types for X_df
X_attrition_df.dtypes


Age                        int64
HourlyRate                 int64
YearsAtCompany             int64
JobLevel                   int64
JobSatisfaction            int64
PerformanceRating          int64
Education                  int64
WorkLifeBalance            int64
DistanceFromHome           int64
YearsSinceLastPromotion    int64
dtype: object

In [35]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_attrition_df, y_attrition_df, test_size=0.2, random_state=42)


In [48]:
# Convert your X data to numeric data types however you see fit
from sklearn.pipeline import Pipeline # Import the Pipeline class
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

numeric_features = selected_columns
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())])
# Add new code cells as necessary
from sklearn.compose import ColumnTransformer
# Import ColumnTransformer if it hasn't been already
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features)])


In [49]:
# Create a StandardScaler

numeric_features = selected_columns
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())])



In [53]:
X_train = pd.DataFrame(X_train, columns=selected_columns)
X_test = pd.DataFrame(X_test, columns=selected_columns)

X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

# X_train = preprocessor.fit_transform(X_train)
# X_test = preprocessor.transform(X_test)

In [54]:
# Create a OneHotEncoder for the Department column
department_encoder = OneHotEncoder(sparse=False)
y_train_department = department_encoder.fit_transform(y_train[['Department']])
y_test_department = department_encoder.transform(y_test[['Department']])

# Fit the encoder to the training data


# Create two new variables by applying the encoder
# to the training and testing data
print("X_train sample:")
print(X_train[:5])
print("y_train_department sample:")
print(y_train_department[:5])




X_train sample:
[[-1.38855944 -0.47283217 -0.97426331 -0.9322736  -1.58233648 -0.42929015
  -0.86335572  0.3574354   1.44039645 -0.67610953]
 [-2.04073779  0.30937375 -1.13857331 -0.9322736   1.15283407 -0.42929015
  -0.86335572  0.3574354  -0.52269928 -0.67610953]
 [-0.84507748 -1.05948661 -0.6456433  -0.02544667  1.15283407 -0.42929015
  -0.86335572  0.3574354   1.31770296 -0.67610953]
 [ 0.24188644 -0.03284134 -0.3170233  -0.02544667 -0.67061296  2.32942686
   0.09993302  0.3574354   0.3361551  -0.35524399]
 [-0.62768469  1.09157967  0.50452672 -0.02544667  0.24111056 -0.42929015
   0.09993302  0.3574354   1.31770296 -0.67610953]]
y_train_department sample:
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [55]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse=False)
y_train_attrition = attrition_encoder.fit_transform(y_train[['Attrition']])
y_test_attrition = attrition_encoder.transform(y_test[['Attrition']])

# Fit the encoder to the training data
print("X_train sample:")
print(X_train[:5])

# Create two new variables by applying the encoder
# to the training and testing data
print("y_train_attrition sample:")
print(y_train_attrition[:5])


X_train sample:
[[-1.38855944 -0.47283217 -0.97426331 -0.9322736  -1.58233648 -0.42929015
  -0.86335572  0.3574354   1.44039645 -0.67610953]
 [-2.04073779  0.30937375 -1.13857331 -0.9322736   1.15283407 -0.42929015
  -0.86335572  0.3574354  -0.52269928 -0.67610953]
 [-0.84507748 -1.05948661 -0.6456433  -0.02544667  1.15283407 -0.42929015
  -0.86335572  0.3574354   1.31770296 -0.67610953]
 [ 0.24188644 -0.03284134 -0.3170233  -0.02544667 -0.67061296  2.32942686
   0.09993302  0.3574354   0.3361551  -0.35524399]
 [-0.62768469  1.09157967  0.50452672 -0.02544667  0.24111056 -0.42929015
   0.09993302  0.3574354   1.31770296 -0.67610953]]
y_train_attrition sample:
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


## Create, Compile, and Train the Model

In [57]:
# Find the number of columns in the X training data
input_shape = X_train.shape[1]

# Create the input layer
input_layer = Input(shape=(input_shape,))

# Create at least two shared layers
shared_layer_1 = Dense(64, activation='relu')(input_layer)
shared_layer_2 = Dense(32, activation='relu')(shared_layer_1)

In [60]:
# Create a branch for Department
# with a hidden layer and an output layer
department_hidden_layer = Dense(16, activation='relu')(shared_layer_2)
department_output_layer = Dense(y_train_department.shape[1], activation='softmax', name='department_output')(department_hidden_layer)

# Create the hidden layer


# Create the output layer



In [59]:
# Create a branch for Attrition
# with a hidden layer and an output layer
attrition_hidden_layer = Dense(16, activation='relu')(shared_layer_2)
attrition_output_layer = Dense(y_train_attrition.shape[1], activation='softmax', name='attrition_output')(attrition_hidden_layer)

# Create the hidden layer


# Create the output layer



In [62]:
# Create the model
model = Model(inputs=input_layer, outputs=[department_output_layer, attrition_output_layer])

# Compile the model
model.compile(optimizer='adam',
              loss={'department_output': 'categorical_crossentropy', 'attrition_output': 'categorical_crossentropy'},
              metrics={'department_output': 'accuracy', 'attrition_output': 'accuracy'})


# Summarize the model
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 10)]                 0         []                            
                                                                                                  
 dense (Dense)               (None, 64)                   704       ['input_1[0][0]']             
                                                                                                  
 dense_1 (Dense)             (None, 32)                   2080      ['dense[0][0]']               
                                                                                                  
 dense_5 (Dense)             (None, 16)                   528       ['dense_1[0][0]']             
                                                                                            

In [64]:
# Train the model
history = model.fit(X_train, {'department_output': y_train_department, 'attrition_output': y_train_attrition},
                    epochs=50, batch_size=32, validation_split=0.2)


Epoch 1/50
30/30 [==============================] - 2s 16ms/step - loss: 1.7119 - department_output_loss: 1.1169 - attrition_output_loss: 0.5949 - department_output_accuracy: 0.4404 - attrition_output_accuracy: 0.7330 - val_loss: 1.3993 - val_department_output_loss: 0.8913 - val_attrition_output_loss: 0.5081 - val_department_output_accuracy: 0.6144 - val_attrition_output_accuracy: 0.7966
Epoch 2/50
30/30 [==============================] - 0s 5ms/step - loss: 1.2685 - department_output_loss: 0.8180 - attrition_output_loss: 0.4505 - department_output_accuracy: 0.6553 - attrition_output_accuracy: 0.8404 - val_loss: 1.3310 - val_department_output_loss: 0.8190 - val_attrition_output_loss: 0.5120 - val_department_output_accuracy: 0.6314 - val_attrition_output_accuracy: 0.7966
Epoch 3/50
30/30 [==============================] - 0s 5ms/step - loss: 1.2133 - department_output_loss: 0.7791 - attrition_output_loss: 0.4342 - department_output_accuracy: 0.6585 - attrition_output_accuracy: 0.8404 - 

In [65]:
# Evaluate the model with the testing data
evaluation = model.evaluate(X_test, {'department_output': y_test_department, 'attrition_output': y_test_attrition})

10/10 [==============================] - 0s 3ms/step - loss: 1.4013 - department_output_loss: 0.9586 - attrition_output_loss: 0.4427 - department_output_accuracy: 0.6259 - attrition_output_accuracy: 0.8605


In [66]:
# Print the accuracy for both department and attrition
print(f"Department prediction accuracy: {evaluation[3]}")
print(f"Attrition prediction accuracy: {evaluation[4]}")

Department prediction accuracy: 0.6258503198623657
Attrition prediction accuracy: 0.8605442047119141


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy is a commonly used metric for classification problems; however, it may not always be the best metric, especially if the dataset is imbalanced. In this project, we are predicting employee attrition and department, both of which might have class imbalances (e.g., fewer people leaving the company than staying, or some departments having significantly more employees than others).

For imbalanced datasets, other metrics such as precision, recall, F1-score, or area under the ROC curve (AUC) might provide better insights into the model's performance. These metrics can help evaluate how well the model handles different classes and avoid misleading conclusions that might arise from using accuracy alone.

2. For both output layers (department and attrition), I chose the softmax activation function. The reasons are as follows:

Softmax for Department Prediction: The department prediction is a multi-class classification problem, where we need to predict one out of several possible departments. The softmax activation function is suitable for this purpose as it outputs a probability distribution across all classes, and the sum of these probabilities equals one. This allows us to select the department with the highest probability as the predicted class.

Softmax for Attrition Prediction: Similarly, although attrition might seem like a binary classification problem, we treated it as a categorical problem with two classes (stay or leave). The softmax activation function ensures that the output provides the probability of each class, making it easy to interpret and handle in a similar manner as the department prediction.

3. Feature Engineering: Creating additional features or selecting more relevant features can improve the model's performance. For example, combining existing features or deriving new features that capture important information about employee behavior.

Handling Imbalanced Data: If the dataset is imbalanced, techniques such as resampling (oversampling the minority class or undersampling the majority class), synthetic data generation (SMOTE), or using class weights can help the model learn better.

Hyperparameter Tuning: Experimenting with different hyperparameters (e.g., number of layers, number of neurons, learning rate, batch size, epochs) can lead to better model performance. Grid search or random search can be used for systematic hyperparameter tuning.

Regularization: Adding regularization techniques such as dropout or L2 regularization can prevent overfitting and improve the generalization of the model.

Ensemble Methods: Combining multiple models (e.g., using ensemble techniques like bagging, boosting, or stacking) can improve the robustness and accuracy of predictions.

Advanced Architectures: Exploring more advanced neural network architectures (e.g., convolutional neural networks (CNNs) for spatial data, recurrent neural networks (RNNs) or transformers for sequential data) could capture more complex patterns in the data.

Cross-Validation: Implementing cross-validation can provide a more robust estimate of the model's performance by ensuring that the model is validated on multiple subsets of the data.

By applying these improvements, the model's predictive performance and generalizability can be significantly enhanced.